baseURL = "https://www.stephenmwangi.com/"
languageCode = "en-us"
title = "Stephen Mwangi"
theme = "hugo-tufte"
math = true
katex = true
rssLimit = 20

[author]
	name = "Stephen Mwangi"

[params]
    subtitle = "Software Engineer & Computer Scientist"
    copyrightHolder = "Stephen Mwangi"
    showPoweredBy = true
    description = "Stephen Mwangi is a software engineer and computer scientist based in Nairobi, Kenya."
    github = "st3v3nmw"

[taxonomies]
  tag = "tags"

[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-paperclip la-lg'></i> "
  weight = -110
  identifier = "about"
  url = "/"
[[menu.nav]]
  name = "Blog"
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = -100
  identifier = "blog"
  url = "/blog"
[[menu.nav]]
  name = "Talks"
  pre = "<i class='fas fa-microphone fa-lg'></i> "
  weight = -90
  identifier = "talks"
  url = "/presentations"
[[menu.nav]]
  name = "Projects"
  pre = "<i class='fas fa-rocket fa-lg'></i> "
  weight = -80
  identifier = "projects"
  url = "/projects"
[[menu.nav]]
  name = "Resumé"
  pre = "<i class='fas fa-briefcase fa-lg'></i> "
  weight = -70
  identifier = "cv"
  url = "/resume.pdf"

[[menu.footer]]
  pre = "<i class='fab fa-linkedin fa-lg'></i> "
  weight = -100
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/stephen-k-mwangi/"
[[menu.footer]]
  pre = "<i class='fas fa-at fa-lg'></i> "
  weight = -90
  identifier = "email"
  url = "mailto:mail@stephenmwangi.com"
[[menu.footer]]
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = -80
  identifier = "rss"
  url = "/index.xml"

# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true
