baseURL = "https://www.stephenmwangi.com/"
languageCode = "en-us"
title = "Stephen Mwangi"
theme = "hugo-tufte"
math = true
katex = true
rssLimit = 20

[author]
	name = "Stephen Mwangi"

[params]
    subtitle = "Software Developer"
    copyrightHolder = "Stephen Mwangi"
    showPoweredBy = true
    description = "Stephen Mwangi is a software developer and computer scientist based in Nairobi, Kenya."
    github = "st3v3nmw"

[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-user-circle la-lg'></i> "
  weight = -110
  identifier = "about"
  url = "/"
[[menu.nav]]
  name = "Projects"
  pre = "<i class='fas fa-laptop-code fa-lg'></i> "
  weight = -90
  identifier = "projects"
  url = "/projects"
[[menu.nav]]
  name = "Random Musings"
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = -100
  identifier = "posts"
  url = "/posts"
[[menu.nav]]
  name = "Resumé"
  pre = "<i class='fas fa-briefcase fa-lg'></i> "
  weight = -80
  identifier = "cv"
  url = "/resume.pdf"

[[menu.footer]]
  pre = "<i class='fas fa-at fa-lg'></i> "
  weight = -100
  identifier = "email"
  url = "mailto:mail@stephenmwangi.com"
[[menu.footer]]
  pre = "<i class='fab fa-linkedin fa-lg'></i> "
  weight = -110
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/stephen-k-mwangi/"
[[menu.footer]]
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = -90
  identifier = "rss"
  url = "/index.xml"

# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true
