baseURL = "https://www.stephenmwangi.com/"
languageCode = "en-us"
title = "Stephen Mwangi"
math = true
katex = true
rssLimit = 10
enableGitInfo = true

[author]
  name = "Stephen Mwangi"

[params]
  copyrightHolder = "Stephen Mwangi"
  description = "Stephen Mwangi is a software engineer and computer scientist based in Nairobi, Kenya"
  license = "CC BY 4.0"
  github = "st3v3nmw"
  bluesky = "stephenmwangi.com"
  linkedin = "stephen-k-mwangi"

[taxonomies]
  tag = "tags"
  topic = "topics"

[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-feather fa-lg'></i> "
  weight = 1
  identifier = "about"
  url = "/"
[[menu.nav]]
  name = "Blog"
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = 2
  identifier = "blog"
  url = "/blog"
[[menu.nav]]
  name = "Talks"
  pre = "<i class='fas fa-microphone-lines fa-lg'></i> "
  weight = 3
  identifier = "talks"
  url = "/talks"
[[menu.nav]]
  name = "Projects"
  pre = "<i class='fas fa-rocket fa-lg'></i> "
  weight = 4
  identifier = "projects"
  url = "/projects"
[[menu.nav]]
  name = "TIL"
  pre  = "<i class='fas fa-lightbulb fa-lg'></i> "
  weight = 5
  identifier = "til"
  url = "/til"

[[menu.footer]]
  pre = "<i class='fas fa-at fa-lg'></i> "
  weight = 1
  identifier = "email"
  url = "mailto:mail@stephenmwangi.com"
[[menu.footer]]
  pre = "<i class='fas fa-rss fa-lg'></i> "
  weight = 2
  identifier = "rss"
  url = "/index.xml"

# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true
